# Generated by Django 4.0 on 2021-12-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
